# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    archive:
        repo: "git://github.com/voxpupuli/puppet-archive"
        ref: "v3.1.0"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"