fixtures:
  repositories:
    archive:
      repo: "git://github.com/voxpupuli/puppet-archive"
      ref: "v4.6.0"
    stdlib: 
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "5.1.0"
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: '4.3.0'
    provision: 'https://github.com/puppetlabs/provision.git'
  forge_modules:
    concat:
      repo: "puppetlabs-concat"
      ref: "6.4.0"
    postgresql:
      repo: "puppetlabs-postgresql"
      ref: "6.8.0"